passenger-update: Make sure PassengerRoot is up-to-date.

diff --git a/passenger-update b/passenger-update
--- a/passenger-update
+++ b/passenger-update
@@ -1,5 +1,8 @@
 #! /bin/bash
 
+PASSENGER_CONF="/etc/apache2/conf.d/passenger"
+[ ! -r "$PASSENGER_CONF" ] && echo "File not found: $PASSENGER_CONF" && exit 1
+
 [ "`id -u`" -ne 0 ] && sudo="sudo"
 
 function step() {
@@ -10,8 +13,15 @@ function step() {
 step "Update Passenger"
 $sudo gem update passenger
 
+version="$(gem specification passenger version | awk '/^ *version:/{print $2}')"
+dirname="$(readlink -f "$(awk '/^PassengerRoot/{print $2}' "$PASSENGER_CONF")")"
+
+if [ "$(basename "$dirname")" != "passenger-$version" ]; then
+  echo "PassengerRoot not up-to-date: $dirname (expected $version)" && exit 1
+fi
+
 step "Install Apache 2 module"
 $sudo passenger-install-apache2-module
 
 step "Restart Apache"
-$sudo /etc/init.d/apache2 restart
+$sudo invoke-rc.d apache2 restart
